version: "2"
services:
  db:
    ports:
      - "5432:5432"
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test

  web:
    build: .
    command: mix phoenix.server
    ports:
      - "4000:4000"
    depends_on:
      - db
